name: Deploy
run-name: Deploy to ${{ github.event.inputs.env }} ${{github.event.inputs.facility }} by @${{ github.actor }}
on:
  workflow_dispatch:
    branches:
      - 'main'
    inputs:
      env:
        type: choice
        description: "Which Environment"
        required: true
        options: 
        - cert
        - prod
      facility:
        description: "Facility Id Prefix"
        required: true
        type: string
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Validate
        if: ${{!fromJson(vars.CLOUDFRONT_IDS)[github.event.inputs.facility]}}
        run: |
          echo "Missing Facility Id in Config"
          exit 1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare the .env file
        env:
          REACT_APP_API_URL: ${{format('https://{0}-api.vpi-cust.insiteflow.io/api/v1', github.event.inputs.facility)}}
        run: |
          echo "Setting env file entry REACT_APP_API_URL to be ${{env.REACT_APP_API_URL}}"
          echo "REACT_APP_API_URL=${{env.REACT_APP_API_URL}}" > .env
          cat .env
      - name: Prepare Task Definition
        uses: nowactions/envsubst@v1
        with:
          input: ./.aws/task-definition.json.tmpl
          output: ./.aws/task-definition.json
        env:
          ENVIRONMENT: ${{ github.event.inputs.env }}
          AWS_REGION: us-east-1
          AWS_ACCOUNT_ID: 360761307738
          FACILITY_ID: ${{ github.event.inputs.facility }}
          FACILITY_SECRETS_ID: backend-saTDSN
          COMMON_SECRETS_ID: common-creds-rS84A6
      - name: Show contents of new task-definition.json
        run: |
          cat ./.aws/task-definition.json
